---
- name: Set cmdline variable to default value
  set_fact:
    cmdline: "{{ __cmdline }}"
  when: cmdline|default(None) == None

- name: Cleanup role default variables
  set_fact:
    __cmdline: !!null

- name: Setup kernel cmdline
  copy:
    content: '{{cmdline}}'
    dest: /boot/firmware/cmdline.txt
  register: cmdline_result

- name: Reboot if kernel cmdline has been changed
  reboot:
  when: cmdline_result.changed == True

- name: Cleanup role variables
  set_fact:
    cmdline: !!null
